after_failure:
    - more .tox/log/* | cat
    - more .tox/*/log/* | cat
before_install:
    - python --version
    - uname -a
    - lsb_release -a
cache: pip
env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
        - SEGFAULT_SIGNALS=all
install:
    - pip install pydistman tox
language: python
matrix:
    include:
        - python: "3.9"
          dist: focal
notifications:
    email:
        on_success: never
        on_failure: always
script:
    - python3 python_pypi_dist_manager.py test
